class Makenote < Formula
  include Language::Python::Virtualenv

  desc "Fast terminal note logging to GitHub"
  homepage "https://github.com/hfinchy12/makenote"
  url "https://github.com/hfinchy12/makenote/archive/refs/tags/v1.2.0.tar.gz"
  # PLACEHOLDER — compute real hash at release time:
  #   curl -sL "https://github.com/hfinchy12/makenote/archive/refs/tags/v0.1.0.tar.gz" \
  #     | shasum -a 256 | awk '{ print $1 }'
  sha256 "1a4ac6f045860fbd78a833c6f5421f899478d7222ff4da79976a3f4cfa230b5b"
  license "MIT"

  depends_on "python@3.12"
  depends_on "gh"

  # Resource stanzas below are generated by:
  #   brew update-python-resources --print-only Formula/makenote.rb
  # Run that command after updating url/sha256 above to refresh these hashes.
resource "click" do
    url "https://files.pythonhosted.org/packages/57/75/31212c6bf2503fdf920d87fee5d7a86a2e3bcf444984126f13d8e4016804/click-8.3.2.tar.gz"
    sha256 "14162b8b3b3550a7d479eafa77dfd3c38d9dc8951f6f69c78913a8f9a7540fd5"
  end

  resource "prompt-toolkit" do
    url "https://files.pythonhosted.org/packages/a1/96/06e01a7b38dce6fe1db213e061a4602dd6032a8a97ef6c1a862537732421/prompt_toolkit-3.0.52.tar.gz"
    sha256 "28cde192929c8e7321de85de1ddbe736f1375148b02f2e17edd840042b1be855"
  end

  resource "questionary" do
    url "https://files.pythonhosted.org/packages/f6/45/eafb0bba0f9988f6a2520f9ca2df2c82ddfa8d67c95d6625452e97b204a5/questionary-2.1.1.tar.gz"
    sha256 "3d7e980292bb0107abaa79c68dd3eee3c561b83a0f89ae482860b181c8bd412d"
  end

  resource "wcwidth" do
    url "https://files.pythonhosted.org/packages/35/a2/8e3becb46433538a38726c948d3399905a4c7cabd0df578ede5dc51f0ec2/wcwidth-0.6.0.tar.gz"
    sha256 "cdc4e4262d6ef9a1a57e018384cbeb1208d8abbc64176027e2c2455c81313159"
  end
  def install
    virtualenv_install_with_resources
  end

  test do
    system bin/"mn", "--version"
  end
end
